### ISSUE TITLE
ERROR: test_PUT_response (sa_api_v2.tests.test_views.TestDataSetInstanceView)

### ISSUE THREAD

**Issue by goldpbear** [mapseed/api#111]
```
======================================================================
ERROR: test_PUT_response (sa_api_v2.tests.test_views.TestDataSetInstanceView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/trevorcroxson/api/src/sa_api_v2/tests/test_views.py", line 3436, in test_PUT_response
    response = self.view(request, **self.request_kwargs)
  File "/Users/trevorcroxson/api/env18/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/trevorcroxson/api/env18/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/trevorcroxson/api/env18/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/trevorcroxson/api/src/sa_api_v2/views/base_views.py", line 587, in dispatch
    return super(OwnedResourceMixin, self).dispatch(request, *args, **kwargs)
  File "/Users/trevorcroxson/api/env18/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/Users/trevorcroxson/api/env18/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/trevorcroxson/api/src/sa_api_v2/views/base_views.py", line 1613, in put
    response = super(DataSetInstanceView, self).put(request, owner_username=owner_username, dataset_slug=dataset_slug)
  File "/Users/trevorcroxson/api/env18/lib/python2.7/site-packages/rest_framework/generics.py", line 289, in put
    return self.update(request, *args, **kwargs)
  File "/Users/trevorcroxson/api/env18/lib/python2.7/site-packages/rest_framework/mixins.py", line 69, in update
    serializer.is_valid(raise_exception=True)
  File "/Users/trevorcroxson/api/env18/lib/python2.7/site-packages/rest_framework/serializers.py", line 213, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/trevorcroxson/api/env18/lib/python2.7/site-packages/rest_framework/serializers.py", line 407, in run_validation
    value = self.to_internal_value(data)
  File "/Users/trevorcroxson/api/src/sa_api_v2/serializers.py", line 1049, in to_internal_value
    return super(DataSetSerializer, self).to_internal_value(data, files)
TypeError: to_internal_value() takes exactly 2 arguments (3 given)
```

**Comment by goldpbear** [comment]
Fixing this error by removing the deprecated `files` argument to `to_internal_value()` reveals an underlying failure:

```
======================================================================
FAIL: test_PUT_response (sa_api_v2.tests.test_views.TestDataSetInstanceView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/trevorcroxson/api/src/sa_api_v2/tests/test_views.py", line 3441, in test_PUT_response
    self.assertStatusCode(response, 301)
  File "/Users/trevorcroxson/api/src/sa_api_v2/tests/test_views.py", line 27, in assertStatusCode
    (expected, response.status_code, response.rendered_content))
AssertionError: Status code not in (301,) response: (400) {"owner":["This field is required."]}
```
