### ISSUE TITLE
ERROR: test_OPTIONS_response_as_owner (sa_api_v2.tests.test_views.TestSubmissionListView)

### ISSUE THREAD

**Issue by dvalp** [mapseed/api#47]
Test `test_OPTIONS_response_as_owner` is failing with `TypeError: __init__() got an unexpected keyword argument 'files'`. This is the first error from running `./manage.py test sa_api_v2.tests.test_views:TestSubmissionListView` which resulted in `FAILED (errors=5, failures=8)`.

```
======================================================================
ERROR: test_OPTIONS_response_as_owner (sa_api_v2.tests.test_views.TestSubmissionListView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ratboy/duwamish/api/src/sa_api_v2/tests/test_views.py", line 2164, in test_OPTIONS_response_as_owner
    response = self.view(request, **self.request_kwargs)
  File "/home/ratboy/.virtualenvs/duwamish-upgrades/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ratboy/.virtualenvs/duwamish-upgrades/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ratboy/.virtualenvs/duwamish-upgrades/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ratboy/duwamish/api/src/sa_api_v2/views/base_views.py", line 727, in dispatch
    response = super(CachedResourceMixin, self).dispatch(request, *args, **kwargs)
  File "/home/ratboy/.virtualenvs/duwamish-upgrades/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ratboy/duwamish/api/src/sa_api_v2/views/base_views.py", line 582, in dispatch
    return super(OwnedResourceMixin, self).dispatch(request, *args, **kwargs)
  File "/home/ratboy/.virtualenvs/duwamish-upgrades/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/ratboy/.virtualenvs/duwamish-upgrades/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ratboy/.virtualenvs/duwamish-upgrades/lib/python2.7/site-packages/rest_framework/views.py", line 477, in options
    data = self.metadata_class().determine_metadata(request, self)
  File "/home/ratboy/.virtualenvs/duwamish-upgrades/lib/python2.7/site-packages/rest_framework/metadata.py", line 69, in determine_metadata
    actions = self.determine_actions(request, view)
  File "/home/ratboy/.virtualenvs/duwamish-upgrades/lib/python2.7/site-packages/rest_framework/metadata.py", line 94, in determine_actions
    serializer = view.get_serializer()
  File "/home/ratboy/duwamish/api/src/sa_api_v2/views/base_views.py", line 1277, in get_serializer
    **kwargs)
  File "/home/ratboy/.virtualenvs/duwamish-upgrades/lib/python2.7/site-packages/rest_framework/serializers.py", line 95, in __init__
    super(BaseSerializer, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'files'
-------------------- >> begin captured logging << --------------------
sa_api_v2.cache: DEBUG: Keys with prefixes "": ""
sa_api_v2.cache: DEBUG: Deleting: "UserCache:17", "user-instance:17", "UserCache:17:_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "": ""
sa_api_v2.cache: DEBUG: Deleting: "UserCache:18:_keys", "user-instance:18", "UserCache:18"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds": "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys"
sa_api_v2.cache: DEBUG: Deleting: "DataSetCache:17:_keys", "dataset-instance:aaron:ds", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "DataSetCache:17", "dataset-permissions:aaron:ds"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds": "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys"
sa_api_v2.cache: DEBUG: Deleting: "DataSetCache:17:_keys", "dataset-instance:aaron:ds", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "DataSetCache:17", "dataset-permissions:aaron:ds"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/places/119": "/api/v2/aaron/datasets/ds/places/119_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds/places/119_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places_keys", "PlaceCache:119", "PlaceCache:119:_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds/places/120", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/actions": "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds/places/120_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/120_keys", "/api/v2/aaron/datasets/ds/places_keys", "PlaceCache:120", "PlaceCache:120:_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/places/119/submissions", "/api/v2/aaron/datasets/ds/places/119", "/api/v2/aaron/datasets/ds/submissions", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/comments", "/api/v2/aaron/datasets/ds/places/119/submissions/121", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds/places/119/comments", "/api/v2/aaron/datasets/ds/places/119/comments/121": "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/comments_keys", "/api/v2/aaron/datasets/ds/places/119/submissions/121_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/places/119/comments/121_keys", "/api/v2/aaron/datasets/ds/places/119_keys", "/api/v2/aaron/datasets/ds/places/119/comments_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/119/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/comments_keys", "/api/v2/aaron/datasets/ds/places/119/submissions/121_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/places/119/comments/121_keys", "/api/v2/aaron/datasets/ds/places/119_keys", "PlaceCache:119:_keys", "SubmissionCache:121", "DataSetCache:17:_keys", "/api/v2/aaron/datasets/ds/places/119/comments_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/119/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys", "SubmissionCache:121:_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/places/119/submissions", "/api/v2/aaron/datasets/ds/places/119", "/api/v2/aaron/datasets/ds/submissions", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/comments", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds/places/119/comments", "/api/v2/aaron/datasets/ds/places/119/comments/122", "/api/v2/aaron/datasets/ds/places/119/submissions/122": "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/comments_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/places/119_keys", "/api/v2/aaron/datasets/ds/places/119/comments/122_keys", "/api/v2/aaron/datasets/ds/places/119/submissions/122_keys", "/api/v2/aaron/datasets/ds/places/119/comments_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/119/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/comments_keys", "PlaceCache:119:_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/places/119_keys", "SubmissionCache:122:_keys", "/api/v2/aaron/datasets/ds/places/119/comments/122_keys", "/api/v2/aaron/datasets/ds/places/119/submissions/122_keys", "/api/v2/aaron/datasets/ds/places/119/comments_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/119/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys", "SubmissionCache:122", "DataSetCache:17:_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/places/119/submissions", "/api/v2/aaron/datasets/ds/places/119", "/api/v2/aaron/datasets/ds/submissions", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/places/119/submissions/123", "/api/v2/aaron/datasets/ds/comments", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds/places/119/comments", "/api/v2/aaron/datasets/ds/places/119/comments/123": "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/comments_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/places/119_keys", "/api/v2/aaron/datasets/ds/places/119/submissions/123_keys", "/api/v2/aaron/datasets/ds/places/119/comments_keys", "/api/v2/aaron/datasets/ds/places/119/comments/123_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/119/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/comments_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/places/119_keys", "SubmissionCache:123:_keys", "PlaceCache:119:_keys", "/api/v2/aaron/datasets/ds/places/119/submissions/123_keys", "DataSetCache:17:_keys", "/api/v2/aaron/datasets/ds/places/119/comments_keys", "/api/v2/aaron/datasets/ds/places/119/comments/123_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/119/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys", "SubmissionCache:123"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/places/119/submissions", "/api/v2/aaron/datasets/ds/places/119/likes/124", "/api/v2/aaron/datasets/ds/places/119", "/api/v2/aaron/datasets/ds/submissions", "/api/v2/aaron/datasets/ds/places/119/submissions/124", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/places/119/likes", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds/likes": "/api/v2/aaron/datasets/ds/places/119/likes/124_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/places/119_keys", "/api/v2/aaron/datasets/ds/places/119/likes_keys", "/api/v2/aaron/datasets/ds/places/119/submissions/124_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/119/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets/ds/likes_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds/places/119_keys", "/api/v2/aaron/datasets/ds/places/119/likes/124_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "SubmissionCache:124:_keys", "PlaceCache:119:_keys", "/api/v2/aaron/datasets/ds/places/119/likes_keys", "/api/v2/aaron/datasets/ds/places/119/submissions/124_keys", "DataSetCache:17:_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "SubmissionCache:124", "/api/v2/aaron/datasets/ds/places/119/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets/ds/likes_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/places/119/submissions", "/api/v2/aaron/datasets/ds/places/119/likes/125", "/api/v2/aaron/datasets/ds/submissions", "/api/v2/aaron/datasets/ds/places/119/submissions/125", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/places/119/likes", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds/places/119", "/api/v2/aaron/datasets/ds/likes": "/api/v2/aaron/datasets/ds/places/119_keys", "/api/v2/aaron/datasets/ds/places/119/submissions/125_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/119/likes_keys", "/api/v2/aaron/datasets/ds/places/119/likes/125_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/119/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets/ds/likes_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds/places/119/submissions/125_keys", "/api/v2/aaron/datasets/ds/actions_keys", "SubmissionCache:125", "/api/v2/aaron/datasets/ds/submissions_keys", "SubmissionCache:125:_keys", "/api/v2/aaron/datasets/ds/places/119_keys", "PlaceCache:119:_keys", "/api/v2/aaron/datasets/ds/places/119/likes_keys", "DataSetCache:17:_keys", "/api/v2/aaron/datasets/ds/places/119/likes/125_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/119/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets/ds/likes_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/places/119/submissions", "/api/v2/aaron/datasets/ds/submissions", "/api/v2/aaron/datasets/ds/places/119/likes/126", "/api/v2/aaron/datasets/ds/places/119", "/api/v2/aaron/datasets/ds/places/119/submissions/126", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/places/119/likes", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds/likes": "/api/v2/aaron/datasets/ds/places/119/likes/126_keys", "/api/v2/aaron/datasets/ds/places/119/submissions/126_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/places/119_keys", "/api/v2/aaron/datasets/ds/places/119/likes_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/119/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets/ds/likes_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds/places/119/likes/126_keys", "/api/v2/aaron/datasets/ds/places/119/submissions/126_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/places/119_keys", "PlaceCache:119:_keys", "/api/v2/aaron/datasets/ds/places/119/likes_keys", "/api/v2/aaron/datasets/ds/places/119/submissions_keys", "DataSetCache:17:_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "SubmissionCache:126:_keys", "SubmissionCache:126", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets/ds/likes_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds", "/api/v2/aaron/datasets/ds/places/119/submissions", "/api/v2/aaron/datasets/ds/places/119/likes/127", "/api/v2/aaron/datasets/ds/places/119", "/api/v2/aaron/datasets/ds/places/119/submissions/127", "/api/v2/aaron/datasets/ds/submissions", "/api/v2/aaron/datasets/ds/actions", "/api/v2/aaron/datasets/ds/places/119/likes", "/api/v2/aaron/datasets/ds/places", "/api/v2/aaron/datasets/ds/likes": "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/actions_keys", "/api/v2/aaron/datasets/ds/places/119/likes/127_keys", "/api/v2/aaron/datasets/ds/places/119/submissions/127_keys", "/api/v2/aaron/datasets/ds/places/119_keys", "/api/v2/aaron/datasets/ds/places/119/likes_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/119/submissions_keys", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets/ds/likes_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds/actions_keys", "SubmissionCache:127:_keys", "/api/v2/aaron/datasets/ds/submissions_keys", "/api/v2/aaron/datasets/ds/places/119/submissions/127_keys", "/api/v2/aaron/datasets/ds/places/119_keys", "PlaceCache:119:_keys", "/api/v2/aaron/datasets/ds/places/119/likes_keys", "DataSetCache:17:_keys", "/api/v2/aaron/datasets/ds/places/119/likes/127_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "/api/v2/aaron/datasets/ds/places/119/submissions_keys", "SubmissionCache:127", "/api/v2/aaron/datasets/ds/places_keys", "/api/v2/aaron/datasets/ds/likes_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds2": "/api/v2/aaron/datasets/ds2_keys", "/api/v2/aaron/datasets_keys"
sa_api_v2.cache: DEBUG: Deleting: "dataset-permissions:aaron:ds2", "/api/v2/aaron/datasets/ds2_keys", "dataset-instance:aaron:ds2", "/api/v2/aaron/datasets_keys", "DataSetCache:18", "DataSetCache:18:_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds2": "/api/v2/aaron/datasets/ds2_keys", "/api/v2/aaron/datasets_keys"
sa_api_v2.cache: DEBUG: Deleting: "dataset-permissions:aaron:ds2", "/api/v2/aaron/datasets/ds2_keys", "dataset-instance:aaron:ds2", "/api/v2/aaron/datasets_keys", "DataSetCache:18", "DataSetCache:18:_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds2/places", "/api/v2/aaron/datasets/ds2/places/128", "/api/v2/aaron/datasets/ds2/actions", "/api/v2/aaron/datasets/ds2": "/api/v2/aaron/datasets/ds2/actions_keys", "/api/v2/aaron/datasets/ds2_keys", "/api/v2/aaron/datasets/ds2/places/128_keys", "/api/v2/aaron/datasets/ds2/places_keys", "/api/v2/aaron/datasets_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds2/actions_keys", "/api/v2/aaron/datasets/ds2/places/128_keys", "PlaceCache:128", "/api/v2/aaron/datasets/ds2_keys", "PlaceCache:128:_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds2/places_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds2/places/128/submissions", "/api/v2/aaron/datasets/ds2", "/api/v2/aaron/datasets/ds2/places/128/comments/129", "/api/v2/aaron/datasets/ds2/places/128", "/api/v2/aaron/datasets/ds2/places/128/submissions/129", "/api/v2/aaron/datasets/ds2/submissions", "/api/v2/aaron/datasets/ds2/actions", "/api/v2/aaron/datasets/ds2/places/128/comments", "/api/v2/aaron/datasets/ds2/places", "/api/v2/aaron/datasets/ds2/comments": "/api/v2/aaron/datasets/ds2/actions_keys", "/api/v2/aaron/datasets/ds2/places/128_keys", "/api/v2/aaron/datasets/ds2/submissions_keys", "/api/v2/aaron/datasets/ds2/comments_keys", "/api/v2/aaron/datasets/ds2/places_keys", "/api/v2/aaron/datasets/ds2_keys", "/api/v2/aaron/datasets/ds2/places/128/submissions/129_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds2/places/128/comments_keys", "/api/v2/aaron/datasets/ds2/places/128/comments/129_keys", "/api/v2/aaron/datasets/ds2/places/128/submissions_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds2/actions_keys", "/api/v2/aaron/datasets/ds2/places/128_keys", "/api/v2/aaron/datasets/ds2/submissions_keys", "SubmissionCache:129:_keys", "/api/v2/aaron/datasets/ds2/comments_keys", "/api/v2/aaron/datasets/ds2/places_keys", "DataSetCache:18:_keys", "/api/v2/aaron/datasets/ds2_keys", "/api/v2/aaron/datasets/ds2/places/128/submissions/129_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds2/places/128/comments_keys", "/api/v2/aaron/datasets/ds2/places/128/comments/129_keys", "/api/v2/aaron/datasets/ds2/places/128/submissions_keys", "SubmissionCache:129", "PlaceCache:128:_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds2/places/128/submissions", "/api/v2/aaron/datasets/ds2", "/api/v2/aaron/datasets/ds2/places/128", "/api/v2/aaron/datasets/ds2/places/128/comments/130", "/api/v2/aaron/datasets/ds2/submissions", "/api/v2/aaron/datasets/ds2/actions", "/api/v2/aaron/datasets/ds2/places/128/comments", "/api/v2/aaron/datasets/ds2/places", "/api/v2/aaron/datasets/ds2/places/128/submissions/130", "/api/v2/aaron/datasets/ds2/comments": "/api/v2/aaron/datasets/ds2/actions_keys", "/api/v2/aaron/datasets/ds2/places/128_keys", "/api/v2/aaron/datasets/ds2/submissions_keys", "/api/v2/aaron/datasets/ds2/comments_keys", "/api/v2/aaron/datasets/ds2/places_keys", "/api/v2/aaron/datasets/ds2_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds2/places/128/comments/130_keys", "/api/v2/aaron/datasets/ds2/places/128/comments_keys", "/api/v2/aaron/datasets/ds2/places/128/submissions_keys", "/api/v2/aaron/datasets/ds2/places/128/submissions/130_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds2/actions_keys", "/api/v2/aaron/datasets/ds2/places/128_keys", "/api/v2/aaron/datasets/ds2/submissions_keys", "/api/v2/aaron/datasets/ds2/comments_keys", "/api/v2/aaron/datasets/ds2/places_keys", "SubmissionCache:130:_keys", "DataSetCache:18:_keys", "/api/v2/aaron/datasets/ds2_keys", "PlaceCache:128:_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds2/places/128/comments/130_keys", "/api/v2/aaron/datasets/ds2/places/128/comments_keys", "SubmissionCache:130", "/api/v2/aaron/datasets/ds2/places/128/submissions_keys", "/api/v2/aaron/datasets/ds2/places/128/submissions/130_keys"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds2/places/128/submissions", "/api/v2/aaron/datasets/ds2", "/api/v2/aaron/datasets/ds2/places/128", "/api/v2/aaron/datasets/ds2/places/128/comments/131", "/api/v2/aaron/datasets/ds2/comments", "/api/v2/aaron/datasets/ds2/submissions", "/api/v2/aaron/datasets/ds2/actions", "/api/v2/aaron/datasets/ds2/places/128/comments", "/api/v2/aaron/datasets/ds2/places", "/api/v2/aaron/datasets/ds2/places/128/submissions/131": "/api/v2/aaron/datasets/ds2/actions_keys", "/api/v2/aaron/datasets/ds2/places/128_keys", "/api/v2/aaron/datasets/ds2/places/128/submissions/131_keys", "/api/v2/aaron/datasets/ds2/submissions_keys", "/api/v2/aaron/datasets/ds2/comments_keys", "/api/v2/aaron/datasets/ds2/places_keys", "/api/v2/aaron/datasets/ds2/places/128/comments/131_keys", "/api/v2/aaron/datasets/ds2_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds2/places/128/comments_keys", "/api/v2/aaron/datasets/ds2/places/128/submissions_keys"
sa_api_v2.cache: DEBUG: Deleting: "/api/v2/aaron/datasets/ds2/actions_keys", "/api/v2/aaron/datasets/ds2/places/128_keys", "/api/v2/aaron/datasets/ds2/places/128/submissions/131_keys", "/api/v2/aaron/datasets/ds2/submissions_keys", "/api/v2/aaron/datasets/ds2/comments_keys", "/api/v2/aaron/datasets/ds2/places_keys", "/api/v2/aaron/datasets/ds2/places/128/comments/131_keys", "SubmissionCache:131:_keys", "/api/v2/aaron/datasets/ds2_keys", "PlaceCache:128:_keys", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds2/places/128/comments_keys", "DataSetCache:18:_keys", "/api/v2/aaron/datasets/ds2/places/128/submissions_keys", "SubmissionCache:131"
sa_api_v2.cache: DEBUG: Keys with prefixes "/api/v2/aaron/datasets", "/api/v2/aaron/datasets/ds": "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys"
sa_api_v2.cache: DEBUG: Deleting: "DataSetCache:17:_keys", "dataset-instance:aaron:ds", "/api/v2/aaron/datasets_keys", "/api/v2/aaron/datasets/ds_keys", "DataSetCache:17", "dataset-permissions:aaron:ds"
oauthlib.oauth2.rfc6749.endpoints.resource: DEBUG: Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x7fd9246dd170>.
--------------------- >> end captured logging << ---------------------
```

**Comment by dvalp** [comment]
Use of `files` as a separate parameter is deprecated in DRF3 as documented [in the release notes](http://www.django-rest-framework.org/topics/3.0-announcement/#request-objects) and [on GitHub](https://github.com/tomchristie/django-rest-framework/issues/2893). All the parsed data should be contained within `request.data`.

**Comment by dvalp** [comment]
This appears to affect the following in ShareaboutsAPI:

- sa_api_v2/serializers.py
- sa_api_v2/views/base_views.py
